@echo off
echo Creating Displexity Installer...

REM Create NSIS installer script
echo ; Displexity Installer Script > installer.nsi
echo ; Generated by create_installer.bat >> installer.nsi
echo. >> installer.nsi
echo !define PRODUCT_NAME "Displexity" >> installer.nsi
echo !define PRODUCT_VERSION "1.0" >> installer.nsi
echo !define PRODUCT_PUBLISHER "Displexity Team" >> installer.nsi
echo !define PRODUCT_WEB_SITE "https://github.com/displexity/displexity" >> installer.nsi
echo !define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\disp.exe" >> installer.nsi
echo !define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" >> installer.nsi
echo !define PRODUCT_UNINST_ROOT_KEY "HKLM" >> installer.nsi
echo. >> installer.nsi
echo SetCompressor lzma >> installer.nsi
echo. >> installer.nsi
echo ; MUI Settings >> installer.nsi
echo !include "MUI2.nsh" >> installer.nsi
echo !define MUI_ABORTWARNING >> installer.nsi
echo !define MUI_ICON "disp.ico" >> installer.nsi
echo !define MUI_UNICON "disp.ico" >> installer.nsi
echo. >> installer.nsi
echo ; Welcome page >> installer.nsi
echo !insertmacro MUI_PAGE_WELCOME >> installer.nsi
echo ; License page >> installer.nsi
echo !insertmacro MUI_PAGE_LICENSE "LICENSE.txt" >> installer.nsi
echo ; Directory page >> installer.nsi
echo !insertmacro MUI_PAGE_DIRECTORY >> installer.nsi
echo ; Instfiles page >> installer.nsi
echo !insertmacro MUI_PAGE_INSTFILES >> installer.nsi
echo ; Finish page >> installer.nsi
echo !define MUI_FINISHPAGE_RUN "$INSTDIR\bin\disp.exe" >> installer.nsi
echo !define MUI_FINISHPAGE_RUN_PARAMETERS "--help" >> installer.nsi
echo !insertmacro MUI_PAGE_FINISH >> installer.nsi
echo. >> installer.nsi
echo ; Uninstaller pages >> installer.nsi
echo !insertmacro MUI_UNPAGE_INSTFILES >> installer.nsi
echo. >> installer.nsi
echo ; Language files >> installer.nsi
echo !insertmacro MUI_LANGUAGE "English" >> installer.nsi
echo. >> installer.nsi
echo ; MUI end ------ >> installer.nsi
echo. >> installer.nsi
echo Name "${PRODUCT_NAME} ${PRODUCT_VERSION}" >> installer.nsi
echo OutFile "displexity-installer.exe" >> installer.nsi
echo InstallDir "$PROGRAMFILES\Displexity" >> installer.nsi
echo InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" "" >> installer.nsi
echo ShowInstDetails show >> installer.nsi
echo ShowUnInstDetails show >> installer.nsi
echo. >> installer.nsi
echo Section "MainSection" SEC01 >> installer.nsi
echo   SetOutPath "$INSTDIR" >> installer.nsi
echo   SetOverwrite ifnewer >> installer.nsi
echo   File /r "release\*.*" >> installer.nsi
echo   CreateDirectory "$SMPROGRAMS\Displexity" >> installer.nsi
echo   CreateShortCut "$SMPROGRAMS\Displexity\Displexity Compiler.lnk" "$INSTDIR\bin\disp.exe" >> installer.nsi
echo   CreateShortCut "$SMPROGRAMS\Displexity\Displexity IDE.lnk" "$INSTDIR\run_ide.bat" >> installer.nsi
echo   CreateShortCut "$DESKTOP\Displexity.lnk" "$INSTDIR\bin\disp.exe" >> installer.nsi
echo SectionEnd >> installer.nsi
echo. >> installer.nsi
echo Section -AdditionalIcons >> installer.nsi
echo   WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}" >> installer.nsi
echo   CreateShortCut "$SMPROGRAMS\Displexity\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url" >> installer.nsi
echo   CreateShortCut "$SMPROGRAMS\Displexity\Uninstall.lnk" "$INSTDIR\uninst.exe" >> installer.nsi
echo SectionEnd >> installer.nsi
echo. >> installer.nsi
echo Section -Post >> installer.nsi
echo   WriteUninstaller "$INSTDIR\uninst.exe" >> installer.nsi
echo   WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\bin\disp.exe" >> installer.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)" >> installer.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe" >> installer.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\bin\disp.exe" >> installer.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}" >> installer.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}" >> installer.nsi
echo   WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}" >> installer.nsi
echo   ; Add to PATH >> installer.nsi
echo   EnVar::SetHKLM >> installer.nsi
echo   EnVar::AddValue "PATH" "$INSTDIR\bin" >> installer.nsi
echo SectionEnd >> installer.nsi
echo. >> installer.nsi

echo Creating LICENSE.txt...
echo MIT License > LICENSE.txt
echo. >> LICENSE.txt
echo Copyright (c) 2026 Displexity Team >> LICENSE.txt
echo. >> LICENSE.txt
echo Permission is hereby granted, free of charge, to any person obtaining a copy >> LICENSE.txt
echo of this software and associated documentation files (the "Software"), to deal >> LICENSE.txt
echo in the Software without restriction, including without limitation the rights >> LICENSE.txt
echo to use, copy, modify, merge, publish, distribute, sublicense, and/or sell >> LICENSE.txt
echo copies of the Software, and to permit persons to whom the Software is >> LICENSE.txt
echo furnished to do so, subject to the following conditions: >> LICENSE.txt
echo. >> LICENSE.txt
echo The above copyright notice and this permission notice shall be included in all >> LICENSE.txt
echo copies or substantial portions of the Software. >> LICENSE.txt

echo.
echo Installer script created: installer.nsi
echo License created: LICENSE.txt
echo.
echo To build installer:
echo 1. Install NSIS (Nullsoft Scriptable Install System)
echo 2. Run: makensis installer.nsi
echo 3. This will create: displexity-installer.exe
echo.
pause